apiVersion: apps/v1
kind: Deployment
metadata:
  name: mscv-stress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mscv-stress
  template:
    metadata:
      labels:
        app: mscv-stress
    spec:
      containers:
        - name: mscv-stress
          image: gcr.io/k8-clusters-474002/mscv-stress:1.0  # Imagen actualizada
          ports:
            - containerPort: 5003
          env:
            - name: ENVIRONMENT
              value: production
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mscv-stress
spec:
  selector:
    app: mscv-stress
  ports:
    - port: 5003
      targetPort: 5003
  type: LoadBalancer  # Expuesto externamente para que el frontend lo consuma
